#!/bin/bash

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=wayland-protocols
VERSION=${VERSION:-1.45}
ORIG_BUILD=1
ORIG_TAG=_slack15.0
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

OUTPUT=${OUTPUT:-/tmp}

set -eu

mkdir -p $OUTPUT

cat $CWD/$PRGNAM-$VERSION-$ARCH-$ORIG_BUILD$ORIG_TAG.$PKGTYPE > \
  $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
